name: Lembrete do PHPSP+Pub

on:
  pull_request:
    branches: [ "master" ]
    
jobs:
  enviar_lembretes_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar lembrete ao canal General
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Dá-lhe manada! :elephpant:! Quinta-feira agora vai rolar o PHPSP + Pub :beers: :phpsp:, nosso evento mensal com breja, php, gente boa e networking."
                  }
                },
                {
                  "type": "section",
                  "block_id": "section567",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Bora fazer o RSVP lá no <https://www.meetup.com/php-sp/|meetup.com>."
                  }
                },
                {
                  "type": "section",
                  "block_id": "section789",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "Te vejo lá :xablau:!"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_GENERAL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
